### ISSUE TITLE
NullPointerException se manca l'entry nel configuration file

### ISSUE THREAD

**Issue by TuraMarco** [gradasso/microservices-commons-utils#4]
Quando chiamo `Configurator.getLongValue(...);` lancia una `NullPointerException`  se non è presente l'entry nel configuration file, viene usato `isEmpty()` senza precedentemente testare che sia diversa da `NULL`, mi pare che lo stesso problema sia presente anche negli altri metodi che recuperano valori diversi da `Long` e che accettano un valore di defoult.

**Comment by christianlusardi** [comment]
ottimo! da fixare!

**Comment by christianlusardi** [comment]
Fixed
